openapi: "3.0.0"
info:
  title: Apigee
  description: description
  version: 1.0.0
servers:
  - url: https://34.160.135.197.nip.io
    description: Optional server description, e.g. Main (production) server
paths:
  /apigee/json:
    get:
      operationId: getPerson
      description: Desc.
      responses:
        '200':
          description: A JSON obj of person
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Person"
components:
  schemas:
    Person:
      properties:
        firstName:
          type: string
        lastName:
          type: string
        city:
          type: string
        state:
          type: string
