---
openapi: "3.0.0"
info:
  title: Odoo AppSheet API
  description: description
  version: 1.0.0
servers:
- url: https://34.160.135.197.nip.io/odoo-appsheet-api2
#- url: https://periscopehomes-feature-normalize-api-7397245.dev.odoo.com/periscope
paths:
  "/sites":
    get:
      tags:
      - Site
      description: Return list of sites.
      summary: Returns list of existing sites.
      operationId: getSites
      parameters:
      - "$ref": "#/components/parameters/limit"
      - "$ref": "#/components/parameters/offset"
      - "$ref": "#/components/parameters/orderBy"
      - "$ref": "#/components/parameters/order"
      - "$ref": "#/components/parameters/select"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SitesResponse"
        '400':
          description: Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/sites/{id}":
    get:
      tags:
      - Site
      description: Return site details.
      summary: Return details for an existing site.
      operationId: getSite
      parameters:
      - "$ref": "#/components/parameters/siteIdPath"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SiteResponse"
        '400':
          description: Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/pallets":
    get:
      tags:
      - Pallet
      description: Return list of pallets.
      summary: Returns list of existing pallets.
      operationId: getPallets
      parameters:
      - "$ref": "#/components/parameters/limit"
      - "$ref": "#/components/parameters/offset"
      - "$ref": "#/components/parameters/orderBy"
      - "$ref": "#/components/parameters/order"
      - "$ref": "#/components/parameters/select"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/PalletsResponse"
        '400':
          description: Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/pallets/{id}":
    get:
      tags:
      - Pallet
      description: Return pallet details.
      summary: Return details for an existing pallet.
      operationId: getPallet
      parameters:
      - "$ref": "#/components/parameters/palletIdPath"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/PalletResponse"
        '400':
          description: Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"

security:
- ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-APIKey
  parameters:
    siteIdPath:
      in: path
      name: id
      description: The site identifier.
      required: true
      schema:
        type: integer
        format: int64
    palletIdPath:
      in: path
      name: id
      description: The pallet identifier.
      required: true
      schema:
        type: integer
        format: int64
    offset:
      in: query
      name: offset
      description: The offset into the table to start the response, if omitted default
        is 0.
      required: false
      schema:
        type: number
        default: 0
    limit:
      in: query
      name: limit
      description: The number of entries to return, if omitted default is 100.
      required: false
      schema:
        type: number
        default: 100
    orderBy:
      in: query
      name: orderBy
      description: Order the results by the provided field name.
      required: false
      schema:
        type: string
        default: id
    order:
      in: query
      name: order
      description: Order the results by either ascending or descending.
      required: false
      schema:
        type: string
        enum:
        - asc
        - desc
    select:
      in: query
      name: select
      description: Specify the comma separated fields to return.
      required: false
      schema:
        type: string
        default: "*"
  schemas:
    Site:
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        code:
          type: string
    SiteResponse:
      "$ref": "#/components/schemas/Site"
    SitesResponse:
      type: object
      properties:
        persons:
          type: array
          items:
            "$ref": "#/components/schemas/Site"
    Pallet:
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        site:
          "$ref": "#/components/schemas/Site"
    PalletResponse:
      "$ref": "#/components/schemas/Pallet"
    PalletsResponse:
      type: object
      properties:
        persons:
          type: array
          items:
            "$ref": "#/components/schemas/Pallet"
    Error:
      type: object
      properties:
        code:
          type: string
        userMessage:
          type: string
        systemMessage:
          type: string
    ErrorResponse:
      type: object
      properties:
        error:
          description: Used to pass error information in a response.
          type: array
          items:
            "$ref": "#/components/schemas/Error"
