openapi: "3.0.0"
info:
  title: Odoo Sites
  description: description
  version: 1.0.0
servers:
  - url: https://34.160.135.197.nip.io
    description: Optional server description, e.g. Main (production) server
paths:
  /odoo-sites/sites:
    get:
      operationId: getSites
      summary: Returns a list of sites.
      description: Desc.
      responses:
        '200':
          description: A JSON array of sites
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sites"
components:
  schemas:
    Site:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        code:
          type: string
    Sites:
      type: array
      items:
        $ref: "#/components/schemas/Site"
